#!/usr/bin/env python3
"""Lists all documents with name starting by Holberton in the collection school."""

import sys
import pymongo

def list_documents_with_prefix(database_name):
    try:
        client = pymongo.MongoClient("mongodb://localhost:27017")
        db = client[database_name]
        collection = db.school
        documents = collection.find({"name": {"$regex": "^Holberton"}})

        for doc in documents:
            print(doc)

    except Exception as e:
        print(f"An error occurred: {e}")
